
services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    
  backend:
    build:
      context: ..                   # root folder
      dockerfile: vegetationFLOW_tool/Dockerfile
    working_dir: /app/vegetationFLOW_tool/backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    volumes:
      - .:/app/vegetationFLOW_tool  # mount your tool folder as volume for live reload
      - ../vegetationFLOW_tool/secrets/earthengine_key.json:/secrets/earthengine_key.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/earthengine_key.json
      
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..                   # root folder
      dockerfile: vegetationFLOW_tool/Dockerfile
    working_dir: /app/vegetationFLOW_tool/frontend
    command: streamlit run Dashboard.py --server.port 8555 --server.address 0.0.0.0 --server.runOnSave true
    depends_on:
      - backend
    volumes:
      - .:/app/vegetationFLOW_tool  # mount your tool folder as volume for live reload
    ports:
      - "8555:8555"



